/** Vocabulary offered in the editor — nudges specs toward consistent wording. */

export const CATEGORIES = [
  'Web landing page',
  'Web app / dashboard',
  'Marketing site',
  'Mobile app screen',
  'Full-page web capture',
  'UI component / detail',
  'Design system page',
  'Email template',
  'Onboarding flow',
  'Settings / preferences',
  'Pricing page',
  'Checkout / payment',
  'Data table / list view',
  'Editor / canvas tool',
];

export const PLATFORMS = [
  'Web — desktop',
  'Web — mobile',
  'Web — full page',
  'Mobile — iOS / Android',
  'Desktop app',
  'Tablet',
  'Terminal / CLI',
];

export const STYLE_KEYWORDS = [
  'minimal',
  'brutalist',
  'glassmorphism',
  'neumorphic',
  'editorial',
  'playful',
  'corporate',
  'retro',
  'high contrast',
  'soft shadows',
  'flat',
  'gradient-heavy',
  'monochrome',
  'rounded',
  'sharp corners',
  'dense data',
  'generous whitespace',
  'illustration-led',
  'photography-led',
  'dark mode',
  'light mode',
];

export const COMPONENTS = [
  'top navigation',
  'sidebar navigation',
  'hero section',
  'primary button',
  'secondary button',
  'input field',
  'search field',
  'card grid',
  'data table',
  'tabs',
  'modal / dialog',
  'dropdown menu',
  'toast / notification',
  'avatar',
  'badge / pill',
  'breadcrumb',
  'pagination',
  'footer',
  'chart',
  'stat tile / KPI',
  'accordion',
  'timeline',
  'empty state',
  'form',
  'toggle / switch',
  'progress bar',
];

export const FONT_STACKS = [
  'Inter',
  'system-ui',
  'SF Pro Text',
  'Roboto',
  'Helvetica Neue',
  'Söhne',
  'Geist',
  'IBM Plex Sans',
  'Satoshi',
  'Poppins',
  'Playfair Display',
  'Georgia',
  'Merriweather',
  'JetBrains Mono',
  'IBM Plex Mono',
  'SF Mono',
];
